[workspace]

resolver = "3"

members = [
    "crates/main/cgp-fork",
    "crates/macros/cgp-fork-macro",
]

[workspace.package]
version         = "0.9.0"
rust-version    = "1.89"
edition         = "2024"
license         = "Apache-2.0"
repository      = "https://github.com/Just-Replicant/cgp-fork"
authors         = ["Just Replicant <Just-Replicant@users.noreply.github.com>"]
homepage        = "https://github.com/Just-Replicant/cgp-fork"
keywords        = ["cgp-fork", "traits", "dsl", "dependency-injection", "macros"]
categories      = ["rust-patterns", "no-std"]

[workspace.dependencies]
cgp-fork       = { version = "0.9.0", path = "./crates/main/cgp-fork" }
cgp-fork-macro = { version = "0.9.0", path = "./crates/macros/cgp-fork-macro" }
