[package]
name         = "cgp-fork-base"
version      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
keywords     = { workspace = true }
categories   = { workspace = true }
description  = "CGP re-exports of the base types, component traits, and core macros."

[dependencies]
cgp-fork-base-types  = { workspace = true }
cgp-fork-component   = { workspace = true }
cgp-fork-macro       = { workspace = true }
