[package]
name         = "cgp-fork-core"
version      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
keywords     = { workspace = true }
categories   = { workspace = true }
description  = "Core CGP facade: components, fields, errors, abstract types, and the core macros."

[dependencies]
cgp-fork-base            = { workspace = true }
cgp-fork-async-macro     = { workspace = true }
cgp-fork-component       = { workspace = true }
cgp-fork-macro           = { workspace = true }
cgp-fork-type            = { workspace = true }
cgp-fork-error           = { workspace = true }
cgp-fork-field           = { workspace = true }
