#![no_std]

/*!
   This crate provides the proc macros used for defining CGP components.
*/

extern crate proc_macro;

use proc_macro::TokenStream;

/**
    `#[cgp_component]` is the most basic macro used to define a CGP component.

    The macro can be used on a Rust trait, which would be used as the base consumer
    trait for the macro to generate the other constructs, including the provider
    trait and the blanket implementations.

    The macro accepts two forms of attribute arguments. If only an identifier is
    provided, the identifier is used as the name of the provider trait. Otherwise,
    the macro accepts a list of key/value pairs, with the following keys allowed:

    - `name` - the name of the component. If not provided, the name would be in the
      format `{provider_trait_name}Component`.

    - `provider` - the name of the provider trait.

    - `context` - the identifier used for the generic context type. If not provided,
      the default identifier `Context` would be used.

    - `derive_delegate` - a list of generic dispatcher wrappers to derive the
      `UseDelegate` pattern on, with the matching generic parameters specified in
      the generic argument of the wrapper. Refer to `UseDelegate` for more details.

    ## Extension Macros

    There are two other macros that extends `#[cgp_component]` that can be used for
    deriving specialized CGP components: [`#[cgp_type]`](macro@cgp_type) can be used to
    define abstract type components, and [`#[cgp_getter]`](macro@cgp_getter) can be used
    to define getter components.

    These macros share the same arguments and expansion as `#[cgp_component]`,
    but also derive additional constructs for the specialized use cases.

    ## Example

    Given the following simplified component definition:

    ```rust,ignore
    #[cgp_component(Greeter)]
    pub trait CanGreet {
        fn greet(&self);
    }
    ```

    is equivalent to the fully explicit definition:

    ```rust,ignore
    #[cgp_component {
        name: GreeterComponent,
        provider: Greeter,
        context: Context,
    }]
    pub trait CanGreet {
        fn greet(&self);
    }
    ```
*/
#[proc_macro_attribute]
pub fn cgp_component(attr: TokenStream, item: TokenStream) -> TokenStream {
    cgp_macro_lib::cgp_component(attr.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

/**
    `#[cgp_provider]` is used when implementing a provider trait.

    It is applied on a provider trait `impl` block, and generates the accompanying
    `IsProviderFor` trait implementation that captures the same constraints as
    specified in the provider trait implementation.

    The macro is mainly used to propagate the provider implementation constraints
    through the `IsProviderFor` trait, so that Rust would print out any unsatisfied
    constraints in the error messages.

    In an ideal world, Rust should be able to print out the unsatisfied constraints,
    even if we don't have an `IsProviderFor` trait. However, since that is not the case,
    the use of this macro is required on all provider trait implementations to ensure
    that the unsatisfied constraints are always printed out.

    The macro accepts an optional identifier as its argument, which is used as the
    component name identifier. If not provided, the component name would default to
    the format `{provider_trait_name}Component`.

    Although the component name may be omitted when using `#[cgp_provider]`, a issue
    that arises is that the default component name identifier cannot be imported
    automatically by Rust Analyzer, due to it being an identifier generated by the
    macro. This means that the user cannot use the quick fix feature to auto import
    the component name, but instead has to add the import statement manually.

    ## Example

    Given the following provider trait implementation:

    ```rust,ignore
    #[cgp_provider]
    impl<Context> Greeter<Context> for GreetName
    where
        Context: HasName,
    {
        fn greet(context: &Context) {
            println!("Hello, {}!", context.name());
        }
    }
    ```

    Is equivalent to the following fully explicit implementation:

    ```rust,ignore
    #[cgp_provider(GreeterComponent)]
    impl<Context> Greeter<Context> for GreetName
    where
        Context: HasName,
    {
        fn greet(context: &Context) {
            println!("Hello, {}!", context.name());
        }
    }
    ```

    Which would generate the following `IsProviderFor` trait implementation:

    ```rust,ignore
    impl<Context> IsProviderFor<GreeterComponent, Context> for GreetName
    where
        Context: HasName,
    {}
*/
#[proc_macro_attribute]
pub fn cgp_provider(attr: TokenStream, item: TokenStream) -> TokenStream {
    cgp_macro_lib::cgp_provider(attr.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro_attribute]
pub fn cgp_new_provider(attr: TokenStream, item: TokenStream) -> TokenStream {
    cgp_macro_lib::cgp_new_provider(attr.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro_attribute]
pub fn cgp_getter(attr: TokenStream, item: TokenStream) -> TokenStream {
    cgp_macro_lib::cgp_getter(attr.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro_attribute]
pub fn cgp_auto_getter(attr: TokenStream, item: TokenStream) -> TokenStream {
    cgp_macro_lib::cgp_auto_getter(attr.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro]
pub fn delegate_components(body: TokenStream) -> TokenStream {
    cgp_macro_lib::delegate_components(body.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro]
pub fn check_components(body: TokenStream) -> TokenStream {
    cgp_macro_lib::check_components(body.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro]
pub fn delegate_and_check_components(body: TokenStream) -> TokenStream {
    cgp_macro_lib::delegate_and_check_components(body.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro]
pub fn cgp_preset(body: TokenStream) -> TokenStream {
    cgp_macro_lib::define_preset(body.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro_attribute]
pub fn cgp_type(attrs: TokenStream, body: TokenStream) -> TokenStream {
    cgp_macro_lib::cgp_type(attrs.into(), body.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro_attribute]
pub fn cgp_context(attr: TokenStream, item: TokenStream) -> TokenStream {
    cgp_macro_lib::cgp_context(attr.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro_attribute]
pub fn blanket_trait(attr: TokenStream, item: TokenStream) -> TokenStream {
    cgp_macro_lib::blanket_trait(attr.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro_attribute]
pub fn re_export_imports(attrs: TokenStream, body: TokenStream) -> TokenStream {
    cgp_macro_lib::re_export_imports(attrs.into(), body.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro]
pub fn replace_with(body: TokenStream) -> TokenStream {
    cgp_macro_lib::replace_with(body.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[proc_macro]
pub fn symbol(body: TokenStream) -> TokenStream {
    cgp_macro_lib::make_symbol(body.into()).into()
}

#[proc_macro]
#[allow(non_snake_case)]
pub fn Product(body: TokenStream) -> TokenStream {
    cgp_macro_lib::make_product_type(body.into()).into()
}

#[proc_macro]
#[allow(non_snake_case)]
pub fn Sum(body: TokenStream) -> TokenStream {
    cgp_macro_lib::make_sum_type(body.into()).into()
}

#[proc_macro]
pub fn product(body: TokenStream) -> TokenStream {
    cgp_macro_lib::make_product_expr(body.into()).into()
}

#[proc_macro_derive(HasField)]
pub fn derive_fields(item: TokenStream) -> TokenStream {
    cgp_macro_lib::derive_fields(item.into()).into()
}

#[proc_macro_derive(HasFields)]
pub fn derive_has_fields(item: TokenStream) -> TokenStream {
    cgp_macro_lib::derive_has_fields(item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}
