[package]
name         = "cgp-extra"
version      = "0.5.0-beta"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
keywords     = { workspace = true }
description  = """
    Context-generic programming extra meta-crate
"""
[features]
default = [ "full" ]
full = [ "cgp-error-extra/alloc" ]

[dependencies]
cgp-core        = { version = "0.5.0-beta" }
cgp-extra-macro = { version = "0.5.0-beta" }
cgp-error-extra = { version = "0.5.0-beta", default-features = false }
cgp-field-extra = { version = "0.5.0-beta" }
cgp-inner       = { version = "0.5.0-beta" }
cgp-run         = { version = "0.5.0-beta" }
cgp-runtime     = { version = "0.5.0-beta" }
cgp-handler     = { version = "0.5.0-beta" }
cgp-monad       = { version = "0.5.0-beta" }
cgp-dispatch    = { version = "0.5.0-beta" }
