[package]
name         = "cgp-fork-macro-test-util-lib"
version      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
keywords     = { workspace = true }
categories   = { workspace = true }
description  = "CGP implementation of the snapshot-testing macros, behind the proc-macro entry points."

[dependencies]
cgp-fork-macro-lib   = { workspace = true }
cgp-fork-macro-core  = { workspace = true }
cgp-fork-extra-macro-lib = { workspace = true }

syn             = { version = "2.0.95" }
quote           = { version = "1.0.38" }
proc-macro2     = { version = "1.0.92" }
prettyplease    = { version = "0.2.37" }
