[package]
name         = "cgp-fork-run"
version      = "0.9.0"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
keywords     = { workspace = true }
categories   = { workspace = true }
description  = "CGP runner component: CanRun and CanSendRun."

[dependencies]
cgp-fork         = { version = "0.9.0", path = "../../main/cgp-fork-core", package = "cgp-fork-core" }
