[package]
name         = "cgp-dispatch"
version      = "0.5.0-beta"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
keywords     = { workspace = true }
description  = "Extensible data type dispatchers for CGP handlers"

[dependencies]
cgp-core    = { version = "0.5.0-beta" }
cgp-monad   = { version = "0.5.0-beta" }
cgp-handler = { version = "0.5.0-beta" }
