[package]
name         = "cgp-core"
version      = "0.8.0-alpha"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
keywords     = { workspace = true }
description  = { workspace = true }

[dependencies]
cgp-base            = { workspace = true }
cgp-async-macro     = { workspace = true }
cgp-component       = { workspace = true }
cgp-macro           = { workspace = true }
cgp-type            = { workspace = true }
cgp-error           = { workspace = true }
cgp-field           = { workspace = true }
