[package]
name         = "cgp-fork-tests"
version      = "0.9.0"
publish      = false
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
keywords     = { workspace = true }
categories   = { workspace = true }
description  = "Integration tests for CGP wiring, behavior, and macro expansions."

[dependencies]
cgp-fork                     = { workspace = true }
cgp-fork-macro-test-util     = { workspace = true }
insta                   = { version = "1.48.0" }
futures                 = { version = "0.3.31" }

[dev-dependencies]
cgp-fork-error-anyhow        = { workspace = true }
cgp-fork-error-eyre          = { workspace = true }
cgp-fork-error-std           = { workspace = true }
cgp-fork-macro-core          = { workspace = true }
syn                     = { version = "2.0.95", features = [ "full", "extra-traits" ] }
quote                   = { version = "1.0.38" }
proc-macro2             = { version = "1.0.92" }
