[package]
name         = "cgp-fork-macro"
version      = "0.9.0"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
keywords     = { workspace = true }
categories   = { workspace = true }
description  = "CGP procedural macros for defining and wiring components."

[lib]
proc-macro = true

[features]
default = []

[dependencies]
syn                     = { version = "2.0.95", features = [ "full", "extra-traits" ] }
cgp-fork-macro-lib           = { workspace = true }
