[package]
name         = "cgp-handler"
version      = "0.8.0-alpha"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
keywords     = { workspace = true }
description  = "Generalized handler interfaces for functional programming"

[dependencies]
cgp         = { version = "0.8.0-alpha", path = "../../main/cgp-core", package = "cgp-core" }
