[package]
name         = "cgp"
version      = "0.8.0-alpha"
readme       = "./README.md"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
keywords     = { workspace = true }
description  = { workspace = true }

[dependencies]
cgp-core       = { workspace = true }
cgp-extra      = { workspace = true }
