[package]
name         = "cgp-compile-fail-tests"
version      = "0.8.0-alpha"
publish      = false
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
keywords     = { workspace = true }
readme       = "./README.md"

[dependencies]
cgp = { workspace = true }
cgp-test-crate-a = { workspace = true }

[dev-dependencies]
trybuild = { version = "1.0.117" }
